# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ParkHere' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ParkHere
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  #Store image in storage
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  #GeoFire using to query nearby location
  pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc'
  pod 'AFNetworking', '~> 3.0'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'GoogleSignIn'
  # to fix error [Permission denied]
  pod 'Alamofire', '~> 4.4'
  pod 'NSDate+TimeAgo'
  # extra input controls
  pod 'TextFieldEffects'
  # multiple selection segment control
  pod 'ATHMultiSelectionSegmentedControl'
  # using rating star bar
  pod 'Cosmos', '~> 8.0'
  # using show date time dialog
  pod 'DatePickerDialog'
  # using to show toast
  pod 'Toast-Swift', '~> 2.0.0'
end
